site_name: Seatizen WIKI
repo_url: https://github.com/SeatizenDOI/wiki-seatizen

# nav:
#   - Home: ./index.md
#   - Before session: ./before-session.md
#   - After session: ./after-session.md
#   - GCP: ./acquisition-gcp.md

theme:
  name: readthedocs